kind: Template
apiVersion: v1
objects:
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "hello-openshift-from-jenkins" 
    spec:
      successfulBuildsHistoryLimit: 2 
      failedBuildsHistoryLimit: 2 
      resources:
        limits:
          cpu: "1" 
          memory: "1024m" 
      source: 
        type: "Git"
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: "http"
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile 
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: hello-backend-from-jenkins
    spec:
      template: 
        metadata:
          labels:
            name: "hello-selector"
        spec:
          containers:
            - name: "hello-service-from-jenkins"
              image: "docker.io/kodcu/hello:latest"
              ports:
                - containerPort: 8080
                  protocol: "TCP"
    replicas: "${{REPLICA_COUNT}}"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "hello-openshift-docker-port-service"
      annotations:
        description: "Exposes the application pod"
    spec:
      ports:
        - name: "from-docker-source"
          port: 8080
          targetPort: 8080
          protocol: "TCP"
      sessionAffinity: None
      type: ClusterIP
      selector:
        name: "hello-selector"
    status:
      loadBalancer: {}
  - kind: Route
    apiVersion: v1
    metadata:
      name: hello-router
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: hello-openshift-docker-port-service
parameters:
  - name: SOURCE_REPOSITORY_URL 
    displayName: Source Repository URL 
    description: The URL of the hello project 
    value: https://github.com/ozlerhakan/hello.git
    required: true 
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "1"
    required: true
message: "ORNEK BIR PROJENIN TEMPLETI"
metadata:
  name: "hello-openshift-jenkinsfile-maven"